import streamlit as st
import os
import json
from PIL import Image
from main_worker import ImplementationWorker

import sys

# Forces the project root into the Python Path
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

# --- 🎨 BRANDING & CONFIG ---
st.set_page_config(
    page_title="PragyanAI Venture Studio | Implementation Core",
    page_icon="⚡",
    layout="wide"
)

# Load and Display Logo
try:
    logo = Image.open("PragyanAI_Transperent.png")
    st.sidebar.image(logo, use_column_width=True)
except FileNotFoundError:
    st.sidebar.warning("Logo not found at assets/PragyanAI_Transperent.png")

st.sidebar.title(" Implementation Core")
st.sidebar.info("Element 2: Automated EDA Synthesis")

# --- 🚀 MAIN UI ---
st.image("PragyanAI_Transperent.png")
st.title("PragyanAI: Hardware Synthesis Factory")
st.markdown("""
This module translates **AI-Architected Plans** into **Physical Engineering Artifacts**.
It generates KiCad-compatible netlists and procurement-ready BOMs.
""")

st.divider()

# --- 📂 FILE UPLOAD SECTION ---
uploaded_file = st.file_uploader("Upload Architecture Plan (JSON)", type=["json"])

if uploaded_file is not None:
    # Save the uploaded plan temporarily
    plan_data = json.load(uploaded_file)
    with open("architecture_plan.json", "w") as f:
        json.dump(plan_data, f)
    
    st.success("✅ Architecture Plan Loaded Successfully!")
    
    # Display Preview of the Plan
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("📋 Project Details")
        st.write(f"**Project Name:** {plan_data.get('project_name', 'Unnamed')}")
        st.write(f"**Target MCU:** {plan_data.get('mcu', {}).get('family', 'Generic')}")
        
    with col2:
        st.subheader("🔌 Interfaces")
        st.json(plan_data.get("interfaces", {}))

    # --- ⚙️ PROCESSING ENGINE ---
    if st.button("🚀 Generate Hardware Artifacts"):
        with st.spinner("Synthesizing Circuit & Mapping Footprints..."):
            try:
                # Initialize the Worker (Element 2 Core)
                worker = ImplementationWorker(plan_path="architecture_plan.json")
                
                # Run the pipeline
                worker.run()
                
                st.balloons()
                st.success("🎯 Synthesis Complete!")
                
                # --- 📦 DOWNLOAD SECTION ---
                st.divider()
                st.subheader("📦 Download Engineering Artifacts")
                
                d_col1, d_col2 = st.columns(2)
                
                # Fetch generated files
                proj_name = plan_data.get("project_name", "PragyanAI_Design")
                netlist_path = f"outputs/netlists/{proj_name}.net"
                bom_path = f"outputs/boms/{proj_name}_BOM.csv"
                
                with d_col1:
                    if os.path.exists(netlist_path):
                        with open(netlist_path, "rb") as f:
                            st.download_button(
                                label="💾 Download KiCad Netlist (.net)",
                                data=f,
                                file_name=f"{proj_name}.net",
                                mime="text/plain"
                            )
                
                with d_col2:
                    if os.path.exists(bom_path):
                        with open(bom_path, "rb") as f:
                            st.download_button(
                                label="📊 Download Procurement BOM (.csv)",
                                data=f,
                                file_name=f"{proj_name}_BOM.csv",
                                mime="text/csv"
                            )
                            
            except Exception as e:
                st.error(f"❌ Synthesis Failed: {str(e)}")

else:
    st.info("Please upload the 'architecture_plan.json' generated by the Planning Engine to begin.")

# --- 📊 STATUS FOOTER ---
st.sidebar.markdown("---")
st.sidebar.write("**System Status:**")
st.sidebar.success("Environment: Python 3.11")
st.sidebar.success("EDA Engine: SKiDL v1.2.1")
